#!/usr/bin/env python3
"""Regenerate requirements*.txt from arqade/libs.py (the single source of truth)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from arqade import libs  # noqa: E402

MARKERS = {
    "linux": "sys_platform == 'linux'",
    "darwin": "sys_platform == 'darwin'",
    "win32": "sys_platform == 'win32'",
    "darwin-arm64": "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "not-darwin": "sys_platform != 'darwin'",
}


def lines(profile: str) -> list[str]:
    out, cat = [], None
    for lib in libs.LIBRARIES:
        if not libs.in_profile(lib, profile):
            continue
        if lib.category != cat:
            cat = lib.category
            out += ["", f"# {cat}"]
        marker = f" ; {MARKERS[lib.only]}" if lib.only else ""
        out.append(f"{lib.pip}{marker}")
    return out


def main() -> None:
    header = "# Generated by scripts/gen_requirements.py from arqade/libs.py - do not edit by hand."
    notes = {
        "requirements-core.txt": ("lite", "# Just enough to run the UI."),
        "requirements.txt": (
            "full",
            "# Everything. Prefer `setup.sh --full` / `setup.bat --full`: it installs package-by-package,\n"
            "# so one failing wheel (e.g. llama-cpp-python without a compiler) never blocks the rest.",
        ),
    }
    for fname, (profile, note) in notes.items():
        (ROOT / fname).write_text("\n".join([header, note, *lines(profile)]) + "\n", encoding="utf-8")
        print(f"wrote {fname}")


if __name__ == "__main__":
    main()
